### ISSUE TITLE
Maximum number of planets?

### ISSUE THREAD

**Issue by GijsMulders** [VirtualPlanetaryLaboratory/vplanet#27]
Is there a limit to the number of simulated planets per system?

I'm getting strange behavior with changing units and unrecognized keywords when using many planets with atmesc, even though the input files are (nearly) identical :

WARNING: dEnvelopeMass < 0 in file p_0.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_1.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_2.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_3.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_4.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_5.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_6.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_7.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_8.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_9.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_10.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_11.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_12.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_13.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_14.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_15.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_16.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_17.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_18.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_19.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_20.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_21.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_22.in, units assumed to be Earth.
WARNING: dEnvelopeMass < 0 in file p_23.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_24.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_25.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_26.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_27.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_28.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_29.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_30.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_31.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_32.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_33.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_34.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_35.in, units assumed to be .in.
WARNING: dEnvelopeMass < 0 in file p_36.in, units assumed to be .in.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_28.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_28.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_29.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_29.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_30.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_30.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_31.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_31.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_32.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_32.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_33.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_33.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_34.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_34.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_35.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_35.in, line 13.
ERROR: Unrecognized option "bHaltEnvelopeGone" in p_36.in, line 11.
ERROR: Unrecognized option "dAtmXAbsEffH" in p_36.in, line 13.

[infiles.zip](https://github.com/VirtualPlanetaryLaboratory/vplanet/files/2725370/infiles.zip)

**Comment by RoryBarnes** [comment]
The problem was indeed that you hit the maximum number of input files. I upped that to 128 and also introduced a helpful error message should someone hit the limit. This issue is resolved by PR #28.
