### ISSUE TITLE
Problem with DeltaT in GalHabit

### ISSUE THREAD

**Issue by NingyiChen** [VirtualPlanetaryLaboratory/vplanet#69]
I have found that time step DeltaT goes down as 1/n for each new calculation in a simulation when running GalHabit module. For example, the time step went from 1000yrs in the beginning down to 0.2 at the end of a 5Gyr simulation.

**Comment by RoryBarnes** [comment]
Thanks for identifying this problem, Ningyi. This bug has been resolved with PR #67.
